[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin",
    "@uniswap/=node_modules/@uniswap",
    "@scroll-tech/=node_modules/@scroll-tech",
]
fs_permissions = [{ access = "read", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
